export const SET_CREATE_POPUP_VISIBLE = 'SET_CREATE_POPUP_VISIBLE';
export const SET_PREVIEW_POPUP_VISIBLE = 'SET_PREVIEW_POPUP_VISIBLE';
export const SET_EDIT_POPUP_VISIBLE = 'SET_EDIT_POPUP_VISIBLE';
export const SET_DELETE_POPUP_VISIBLE = 'SET_DELETE_POPUP_VISIBLE';
export const SET_ALL_POPUPS_UNVISIBLE = 'SET_ALL_POPUPS_UNVISIBLE';

// export const TOGGLE_RANGE_VISIBLE = 'TOGGLE_RANGE_VISIBLE';
export const SET_START_OF_RANGE = 'SET_START_OF_RANGE';
export const SET_END_OF_RANGE = 'SET_END_OF_RANGE';
export const SET_LEFT_DATEPICKER_VISIBLE = 'SET_LEFT_DATEPICKER_VISIBLE';
export const SET_RIGHT_DATEPICKER_VISIBLE = 'SET_RIGHT_DATEPICKER_VISIBLE';
// export const SET_RADIO_BTN_VALUE = 'SET_RADIO_BTN_VALUE';
export const SET_NEXT_DAYS_NUM = 'SET_NEXT_DAYS_NUM';
export const SET_NEXT_EVENTS_NUM = 'SET_NEXT_EVENTS_NUM';
export const SET_SELECT_VALUE = 'SET_SELECT_VALUE';

export const SET_DATE = 'SET_DATE';
export const SET_VISIBLE = 'SET_VISIBLE';

export const CREATE_EVENT = 'CREATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const SET_ROW_DATE = 'SET_ROW_DATE';

export const FETCH_EVENTS_REQUESTED = 'FETCH_EVENTS_REQUESTED';
export const FETCH_EVENTS_LOADED = 'FETCH_EVENTS_LOADED';
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR';
